language: java
script: true
before_deploy: mvn clean package
deploy:
  provider: releases
  api_key:
    secure: QfmRZVhnvsk+Z+vCjVFz/8PjXo7jKR8U9UOJlmDWRQEt3+QSkSApzxDEYGy4K7YvThf4kHjQpKDqm9E6apdd0SRoJ8ybnssBJ8B22m01I3lY9pJjZdRhMzqW7a5q6tJ7crHPKSqKusb4knEVL2rga0UMrG4KAvbH1Rx9a5xG2PqD0ZUtfDotyt1CuYk3t0vxfOEbPGmkWTf1L3U8rluFq3pXmdwrxhAblCVVNiALTo1NogG1w9pWP6TyJY+ElUnV17tlZil+z/ASENKESuIRPPBMXvhubAajWWdMogR8a3PolwFQmJAUbGPzu6VSwWmsQCtKFSbquLSxVH/Ue7yz6sApsd8UKW+Y5+XTvYLnjJjxDsozek7ENlIrS7EqPxy+Jd185CbuJ92kDucsKBPxun9iyNzoO1OYVPcS5Ft4MAoQ3EafNVq2eW2FJ/ywbeYpkARx3J7ldIyvwN2toH9uVPsBv7aD5O5vFQUyS/jmcFV+KlrqDqnBeI6RAbC3lwbpteU3Oh5U06TFNH/py9DSRN4S+WYIp/epiUnGItjZXmE8rw8AHV3D0YN+6GgszfaV8iEXEViu0HdKA8PnwC2Om+TOJgQDPkwUi0kqveO6pXRaFt0G4GHyO62b7c1eysSMP0ArTlDkeFASX9BjC9JW1+mnFIa5qeqGZlXEulsxmnc=
  file: src/target/octo-pnp.zip
  skip_cleanup: true
  on:
    repo: skbkontur/OctoPnP
    tags: true